// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrIN0k4ZHL12wlOTz7-0XRK37TvbhSxEY',
    appId: '1:970534731512:web:47348ddeeb83c0698b450d',
    messagingSenderId: '970534731512',
    projectId: 'emmi-eb98a',
    authDomain: 'emmi-eb98a.firebaseapp.com',
    storageBucket: 'emmi-eb98a.firebasestorage.app',
    measurementId: 'G-NR8ZE2408E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_fm-7leX63zgr5FjzJVDDjflT9trElKM',
    appId: '1:970534731512:android:104635e11aa0aed28b450d',
    messagingSenderId: '970534731512',
    projectId: 'emmi-eb98a',
    storageBucket: 'emmi-eb98a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDB4sF_zr0FItXdY10cSPHxmPaXW-DFI',
    appId: '1:970534731512:ios:eee2e96e2a736bb68b450d',
    messagingSenderId: '970534731512',
    projectId: 'emmi-eb98a',
    storageBucket: 'emmi-eb98a.firebasestorage.app',
    iosBundleId: 'com.example.emmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDB4sF_zr0FItXdY10cSPHxmPaXW-DFI',
    appId: '1:970534731512:ios:eee2e96e2a736bb68b450d',
    messagingSenderId: '970534731512',
    projectId: 'emmi-eb98a',
    storageBucket: 'emmi-eb98a.firebasestorage.app',
    iosBundleId: 'com.example.emmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrIN0k4ZHL12wlOTz7-0XRK37TvbhSxEY',
    appId: '1:970534731512:web:4b9c1056964aff488b450d',
    messagingSenderId: '970534731512',
    projectId: 'emmi-eb98a',
    authDomain: 'emmi-eb98a.firebaseapp.com',
    storageBucket: 'emmi-eb98a.firebasestorage.app',
    measurementId: 'G-4QDMHQ611Q',
  );
}
